WINDOW_WIDTH = love.graphics.getWidth()
WINDOW_HEIGHT = love.graphics.getHeight()

ENEMY_COUNT = 100
ENEMY_MAX_VELOCITY = 50
ENEMY_SIZE = 10
BLOOD_SPLASH_TIMEOUT = 5
BLOOD_SPLASH_COUNT = 20
WORLD_SIZE_FACTOR = 5

PLAYER_MAX_VELOCITY = 300
PLAYER_SIZE = 7
PLAYER_AXE_SIZE = 14

WEAPON_SIZE_FACTOR = 3.10639309197 * 2
WEAPON_SWING_SPEED = 45

TOWER_REPAIR_SPEED = 1
TOWER_DAMAGE_SPEED = 0.2
DAMAGE_INCREASE_RATE = 0.01

gameOver = -1
