WINDOW_WIDTH = love.graphics.getWidth()
WINDOW_HEIGHT = love.graphics.getHeight()

ENEMY_COUNT = 100
ENEMY_MAX_VELOCITY = 50
ENEMY_SIZE = 10

WORLD_SIZE_FACTOR = 5

PLAYER_MAX_VELOCITY = 200
PLAYER_SIZE = 10

WEAPON_SIZE_FACTOR = 6
WEAPON_SWING_SPEED = 20

TOWER_REPAIR_SPEED = 1
TOWER_DAMAGE_SPEED = 0.2
DAMAGE_INCREASE_RATE = 0.01
